<a href="https://colab.research.google.com/github/DilushkumarVasu/Pandas/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Loading in Data

In [2]:
import pandas as pd

In [3]:
!wget -O sbux.csv https://raw.githubusercontent.com/PyDataWorkshop/datasets/master/sbux.csv

--2024-10-29 14:56:00--  https://raw.githubusercontent.com/PyDataWorkshop/datasets/master/sbux.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 8510 (8.3K) [text/plain]
Saving to: ‘sbux.csv’

sbux.csv            100%[===================>]   8.31K  --.-KB/s    in 0s

2024-10-29 14:56:00 (102 MB/s) - ‘sbux.csv’ saved [8510/8510]

In [4]:
df = pd.read_csv('sbux.csv')

In [5]:
df = pd.read_csv('https://raw.githubusercontent.com/PyDataWorkshop/datasets/master/sbux.csv')

In [20]:
type(df)

pandas.core.frame.DataFrame

In [34]:
!head sbux.csv

Date,Open,High,Low,Close,Volume,Adj Close
03/03/2008,18.02,18.5,16.77,17.5,15459300,16.83
01/02/2008,18.97,19.35,17.75,17.98,13260300,17.29
02/01/2008,20.14,21.01,17.66,18.91,24534800,18.19
03/12/2007,23.23,23.43,19.89,20.47,12201200,19.69
01/11/2007,26.4,26.68,21.77,23.39,20232800,22.49
01/10/2007,26.27,26.92,25.63,26.68,9327000,25.66
04/09/2007,27.67,28.19,25.95,26.2,11225900,25.2
01/08/2007,26.51,28.6,26.03,27.55,12381800,26.49
02/07/2007,26.4,28.5,25.63,26.68,16492900,25.66

In [36]:
df.head(10)#by default it gives first 5 records

         Date   Open   High    Low  Close    Volume  Adj Close
0  03/03/2008  18.02  18.50  16.77  17.50  15459300      16.83
1  01/02/2008  18.97  19.35  17.75  17.98  13260300      17.29
2  02/01/2008  20.14  21.01  17.66  18.91  24534800      18.19
3  03/12/2007  23.23  23.43  19.89  20.47  12201200      19.69
4  01/11/2007  26.40  26.68  21.77  23.39  20232800      22.49
5  01/10/2007  26.27  26.92  25.63  26.68   9327000      25.66
6  04/09/2007  27.67  28.19  25.95  26.20  11225900      25.20
7  01/08/2007  26.51  28.60  26.03  27.55  12381800      26.49
8  02/07/2007  26.40  28.50  25.63  26.68  16492900      25.66
9  01/06/2007  28.80  29.15  25.22  26.24  18001300      25.23

In [37]:
df.tail()

           Date   Open   High    Low  Close   Volume  Adj Close
176  01/07/1993  48.75  54.00  47.50  47.50  7049900       1.43
177  01/06/1993  48.00  49.75  44.50  49.00  4878800       1.47
178  03/05/1993  39.50  48.75  39.00  48.00  8201600       1.44
179  01/04/1993  38.00  40.25  34.25  38.75  4457200       1.16
180  31/03/1993  37.25  38.25  37.00  38.00  4550400       1.14

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 181 entries, 0 to 180
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       181 non-null    object
 1   Open       181 non-null    float64
 2   High       181 non-null    float64
 3   Low        181 non-null    float64
 4   Close      181 non-null    float64
 5   Volume     181 non-null    int64
 6   Adj Close  181 non-null    float64
dtypes: float64(5), int64(1), object(1)
memory usage: 10.0+ KB

# Selecting Rows and Columns

In [39]:
df[0,0]

KeyError: (0, 0)

In [9]:
df.columns

Index(['date', 'open', 'high', 'low', 'close', 'volume', 'adj close'], dtype='object')

In [7]:
 df.columns = ['date', 'open', 'high', 'low', 'close', 'volume', 'adj close']#can do assignment operation

In [12]:
df.head()

         date   open   high    low  close    volume  adj close
0  03/03/2008  18.02  18.50  16.77  17.50  15459300      16.83
1  01/02/2008  18.97  19.35  17.75  17.98  13260300      17.29
2  02/01/2008  20.14  21.01  17.66  18.91  24534800      18.19
3  03/12/2007  23.23  23.43  19.89  20.47  12201200      19.69
4  01/11/2007  26.40  26.68  21.77  23.39  20232800      22.49

In [44]:
df['open']

0      18.02
1      18.97
2      20.14
3      23.23
4      26.40
       ...
176    48.75
177    48.00
178    39.50
179    38.00
180    37.25
Name: open, Length: 181, dtype: float64

In [51]:
type(df['open'])

pandas.core.series.Series

In [46]:
df[['open','date']]

      open        date
0    18.02  03/03/2008
1    18.97  01/02/2008
2    20.14  02/01/2008
3    23.23  03/12/2007
4    26.40  01/11/2007
..     ...         ...
176  48.75  01/07/1993
177  48.00  01/06/1993
178  39.50  03/05/1993
179  38.00  01/04/1993
180  37.25  31/03/1993

[181 rows x 2 columns]

In [53]:
type(df[['open', 'date']])

pandas.core.frame.DataFrame

In [48]:
df.loc[:, ['open', 'date']]

      open        date
0    18.02  03/03/2008
1    18.97  01/02/2008
2    20.14  02/01/2008
3    23.23  03/12/2007
4    26.40  01/11/2007
..     ...         ...
176  48.75  01/07/1993
177  48.00  01/06/1993
178  39.50  03/05/1993
179  38.00  01/04/1993
180  37.25  31/03/1993

[181 rows x 2 columns]

In [56]:
df.iloc[0]#0th row of the data frame, but .iloc is used for positional based indexing

date         03/03/2008
open              18.02
high               18.5
low               16.77
close              17.5
volume         15459300
adj close         16.83
Name: 0, dtype: object

In [59]:
df.loc[0]#0th row of the dataframe, but .loc is used for for label-based indexing, this dataframe contains by default the integder indexing so both are same results

date         03/03/2008
open              18.02
high               18.5
low               16.77
close              17.5
volume         15459300
adj close         16.83
Name: 0, dtype: object

In [60]:
df.loc['test']

KeyError: 'test'

In [15]:
df2 = pd.read_csv('sbux.csv',index_col='Date')

In [16]:
df2.head()

             Open   High    Low  Close    Volume  Adj Close
Date
03/03/2008  18.02  18.50  16.77  17.50  15459300      16.83
01/02/2008  18.97  19.35  17.75  17.98  13260300      17.29
02/01/2008  20.14  21.01  17.66  18.91  24534800      18.19
03/12/2007  23.23  23.43  19.89  20.47  12201200      19.69
01/11/2007  26.40  26.68  21.77  23.39  20232800      22.49

In [19]:
df2.loc['03/03/2008']

Open               18.02
High               18.50
Low                16.77
Close              17.50
Volume       15459300.00
Adj Close          16.83
Name: 03/03/2008, dtype: float64

In [20]:
type(df2.loc['03/03/2008'])

pandas.core.series.Series

In [22]:
df[df['open']>34]

           date   open   high    low  close    volume  adj close
13   01/02/2007  35.13  35.42  30.24  30.90  10784200      29.72
14   03/01/2007  35.60  36.61  33.49  34.94   8635100      33.60
15   01/12/2006  35.25  37.14  34.90  35.42   5455800      34.06
16   01/11/2006  37.99  40.01  35.16  35.29   8192600      33.94
17   02/10/2006  34.15  39.50  33.61  37.75   8627800      36.30
..          ...    ...    ...    ...    ...       ...        ...
176  01/07/1993  48.75  54.00  47.50  47.50   7049900       1.43
177  01/06/1993  48.00  49.75  44.50  49.00   4878800       1.47
178  03/05/1993  39.50  48.75  39.00  48.00   8201600       1.44
179  01/04/1993  38.00  40.25  34.25  38.75   4457200       1.16
180  31/03/1993  37.25  38.25  37.00  38.00   4550400       1.14

[80 rows x 7 columns]

In [23]:
df[df['open']>64]

Empty DataFrame
Columns: [date, open, high, low, close, volume, adj close]
Index: []

In [24]:
df['open']>64

0      False
1      False
2      False
3      False
4      False
       ...
176    False
177    False
178    False
179    False
180    False
Name: open, Length: 181, dtype: bool

In [25]:
type(df['open']>64)

pandas.core.series.Series

In [28]:
import numpy as np
A = np.arange(10)
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
A[A%2==0]

array([0, 2, 4, 6, 8])

In [30]:
type(A%2==0)

numpy.ndarray

In [31]:
df.values

array([['03/03/2008', 18.02, 18.5, ..., 17.5, 15459300, 16.83],
       ['01/02/2008', 18.97, 19.35, ..., 17.98, 13260300, 17.29],
       ['02/01/2008', 20.14, 21.01, ..., 18.91, 24534800, 18.19],
       ...,
       ['03/05/1993', 39.5, 48.75, ..., 48.0, 8201600, 1.44],
       ['01/04/1993', 38.0, 40.25, ..., 38.75, 4457200, 1.16],
       ['31/03/1993', 37.25, 38.25, ..., 38.0, 4550400, 1.14]],
      dtype=object)

In [33]:
A = df[['open','close']].values

In [34]:
A

array([[18.02, 17.5 ],
       [18.97, 17.98],
       [20.14, 18.91],
       [23.23, 20.47],
       [26.4 , 23.39],
       [26.27, 26.68],
       [27.67, 26.2 ],
       [26.51, 27.55],
       [26.4 , 26.68],
       [28.8 , 26.24],
       [31.16, 28.81],
       [31.54, 31.02],
       [30.2 , 31.36],
       [35.13, 30.9 ],
       [35.6 , 34.94],
       [35.25, 35.42],
       [37.99, 35.29],
       [34.15, 37.75],
       [31.61, 34.05],
       [33.99, 31.01],
       [37.96, 34.23],
       [35.49, 37.76],
       [37.63, 35.65],
       [37.98, 37.27],
       [36.33, 37.63],
       [31.28, 36.32],
       [30.57, 31.7 ],
       [30.34, 30.01],
       [28.3 , 30.45],
       [50.31, 28.28],
       [49.8 , 50.1 ],
       [52.55, 49.03],
       [51.73, 52.55],
       [54.92, 51.66],
       [49.9 , 54.79],
       [52.23, 49.52],
       [51.89, 51.66],
       [54.16, 51.81],
       [63.29, 54.  ],
       [56.33, 62.36],
       [52.92, 56.26],
       [45.97, 52.88],
       [42.99, 45.46],
       [46.87, 43.24],
       [44.65, 46.99],
       [40.7 , 43.49],
       [38.82, 40.6 ],
       [38.14, 38.92],
       [37.89, 37.87],
       [36.82, 37.4 ],
       [33.45, 36.61],
       [32.08, 33.16],
       [31.36, 32.17],
       [29.04, 31.6 ],
       [28.09, 28.8 ],
       [27.4 , 28.39],
       [24.95, 27.33],
       [24.56, 24.55],
       [23.42, 24.67],
       [25.81, 23.51],
       [23.62, 25.76],
       [22.67, 23.45],
       [20.47, 22.72],
       [22.  , 20.38],
       [24.05, 21.74],
       [20.66, 23.84],
       [19.99, 20.66],
       [19.52, 20.1 ],
       [24.42, 19.63],
       [24.3 , 24.85],
       [22.85, 24.28],
       [23.07, 22.82],
       [23.56, 23.13],
       [22.82, 23.01],
       [19.11, 23.77],
       [17.63, 19.05],
       [17.15, 17.72],
       [14.8 , 17.12],
       [16.86, 14.94],
       [18.13, 16.87],
       [22.49, 18.04],
       [20.  , 23.  ],
       [19.35, 19.52],
       [42.56, 19.35],
       [47.5 , 42.44],
       [49.38, 47.63],
       [43.92, 49.94],
       [46.25, 44.25],
       [44.31, 45.56],
       [40.13, 44.69],
       [38.25, 40.06],
       [37.47, 36.63],
       [38.  , 37.5 ],
       [34.13, 38.19],
       [31.  , 34.  ],
       [40.19, 30.23],
       [35.13, 44.81],
       [31.75, 35.13],
       [23.87, 32.  ],
       [26.56, 24.25],
       [26.87, 26.56],
       [24.75, 27.19],
       [22.94, 24.78],
       [23.5 , 22.87],
       [24.27, 23.25],
       [36.88, 37.56],
       [37.5 , 36.88],
       [28.25, 36.94],
       [53.38, 28.06],
       [52.13, 52.88],
       [55.63, 52.06],
       [47.06, 56.13],
       [43.63, 46.13],
       [35.5 , 43.38],
       [31.87, 36.19],
       [42.19, 31.56],
       [53.63, 41.88],
       [47.63, 53.44],
       [48.25, 48.  ],
       [45.38, 48.13],
       [39.56, 45.31],
       [37.  , 39.56],
       [38.38, 36.56],
       [35.63, 38.38],
       [33.13, 34.88],
       [41.63, 33.  ],
       [41.13, 41.81],
       [40.75, 41.  ],
       [39.  , 40.94],
       [31.62, 38.94],
       [29.87, 31.5 ],
       [29.62, 29.87],
       [33.63, 29.62],
       [34.25, 33.63],
       [28.62, 34.25],
       [34.88, 28.62],
       [32.63, 34.63],
       [33.  , 32.5 ],
       [32.25, 33.  ],
       [26.  , 32.75],
       [28.12, 26.  ],
       [27.12, 28.25],
       [27.37, 27.12],
       [24.62, 27.12],
       [18.12, 23.31],
       [16.87, 17.62],
       [21.  , 16.75],
       [42.13, 21.  ],
       [39.38, 42.25],
       [38.38, 39.25],
       [40.  , 37.88],
       [37.38, 40.  ],
       [35.75, 37.38],
       [29.06, 35.63],
       [23.62, 29.06],
       [24.  , 23.5 ],
       [24.  , 24.  ],
       [23.87, 23.87],
       [27.25, 24.  ],
       [26.75, 27.5 ],
       [26.75, 26.81],
       [23.  , 27.12],
       [28.  , 23.06],
       [29.25, 28.25],
       [25.25, 29.  ],
       [28.5 , 25.25],
       [29.5 , 28.5 ],
       [23.5 , 29.75],
       [22.75, 24.37],
       [24.  , 23.25],
       [22.  , 24.  ],
       [22.75, 22.25],
       [26.25, 22.25],
       [27.5 , 26.75],
       [48.25, 27.37],
       [48.25, 48.5 ],
       [48.75, 47.5 ],
       [48.  , 49.  ],
       [39.5 , 48.  ],
       [38.  , 38.75],
       [37.25, 38.  ]])

In [35]:
type(A)

numpy.ndarray

In [36]:
smalldf = df[['open','close']]
smalldf.to_csv('output.csv')

In [37]:
!head output.csv

,open,close
0,18.02,17.5
1,18.97,17.98
2,20.14,18.91
3,23.23,20.47
4,26.4,23.39
5,26.27,26.68
6,27.67,26.2
7,26.51,27.55
8,26.4,26.68

In [40]:
smalldf.to_csv('output.csv',index=False)
!head output.csv

open,close
18.02,17.5
18.97,17.98
20.14,18.91
23.23,20.47
26.4,23.39
26.27,26.68
27.67,26.2
26.51,27.55
26.4,26.68